### ISSUE TITLE
How to use？

### ISSUE THREAD

**Issue by c61292558** [robert-ancell/x11.dart#17]
After looking at the API documentation, I couldn't figure out how to use it, and it was hard to see what each class or method did.
Is there a more detailed code example?
thank you .

**Comment by robert-ancell** [comment]
See the [examples](https://github.com/flutter/flutter/issues/142916). This library doesn't provided detailed information about how X11 works, see the [specification](https://www.x.org/releases/X11R7.5/doc/x11proto/proto.pdf) or other online documentation for this. Hope this helps!
