### ISSUE TITLE
Connect using TCP

### ISSUE THREAD

**Issue by robert-ancell** [robert-ancell/x11.dart#2]

**Comment by robert-ancell** [comment]
TCP is required for using X11 on Windows.

**Comment by robert-ancell** [comment]
Ah. right. I'll check what the other X11 libraries do on Windows for the default authority file.

**Comment by hanskokx** [comment]
@robert-ancell It's still looking for .Xauthority

**Comment by robert-ancell** [comment]
@hanskokx ah, it should still try the default but ignore it if it doesn't load. Try x11 0.1.3!
